INSERT INTO `Parts` (`PartName`, `PartDescription`, `PartMaterialType`, `PartColor`) VALUES
    ('Cartridge Body', NULL, NULL, NULL),
    ('Cartridge Cap', NULL, NULL, NULL),
    ('Writing Tip', 'Gen. 2 tip', NULL, NULL),
    ('Ink', NULL, NULL, 'Black'),
    ('Barrel Bottom', NULL, 'Plastic', 'Red'),
    ('Barrel Top', NULL, 'Plastic', 'Red'),
    ('Barrel Bottom', NULL, 'Metal', 'Red'),
    ('Barrel Top', NULL, 'Metal', 'Red'),
    ('Barrel Bottom', NULL, 'Plastic', 'Blue'),
    ('Barrel Top', NULL, 'Plastic', 'Blue'),
    ('Barrel Bottom', NULL, 'Metal', 'Blue'),
    ('Barrel Top', NULL, 'Metal', 'Blue'),
    ('Pocket Clip', NULL, NULL, NULL),
    ('Thruster', NULL, NULL, NULL),
    ('Cam', NULL, 'Metal', NULL),
    ('Spring', NULL, NULL, NULL),
    ('Rubber Grip', NULL, NULL, 'Black'),
    ('Box Top', 'Standard', NULL, NULL),
    ('Box Bottom', 'Standard', NULL, NULL),
    ('Box Insert', 'Standard', NULL, NULL),
    ('Barrel Bottom', NULL, 'Plastic', 'Turquoise'),
    ('Barrel Top', NULL, 'Plastic', 'Turquoise'),
    ('Writing Tip', 'Gen. 1 tip', NULL, NULL);

INSERT INTO `Assemblies` (`AssemblyName`) VALUES
    ('InkCartridge'),
    ('PenAssembly'),
    ('PenAssembly'),
    ('PenAssembly'),
    ('PenAssembly'),
    ('PenPackage'),
    ('PenPackage'),
    ('PenPackage'),
    ('PenPackage'),
    ('PenPackage'),
    ('PenPackage');


INSERT INTO `PartAssemblies` (`AssemblyId`, `PartId`) VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 4),
    (2, 5),
    (2, 6),
    (2, 13),
    (2, 14),
    (2, 15),
    (2, 16),
    (2, 17),
    (3, 7),
    (3, 8),
    (3, 13),
    (3, 14),
    (3, 15),
    (3, 16),
    (3, 17),
    (4, 9),
    (4, 10),
    (4, 13),
    (4, 14),
    (4, 15),
    (4, 16),
    (4, 17),
    (5, 11),
    (5, 12),
    (5, 13),
    (5, 14),
    (5, 15),
    (5, 16),
    (5, 17),
    (6, 18),
    (6, 19),
    (6, 20),
    (7, 18),
    (7, 19),
    (7, 20),
    (8, 19),
    (8, 20),
    (10, 18),
    (10, 19),
    (10, 20),
    (11, 18),
    (11, 19),
    (11, 20)
    ;

INSERT INTO AssemblyParents (`AssemblyId`, `ParentAssemblyId`) VALUES
    (6, NULL),
    (2, 6),
    (1, 2),
    (7, NULL),
    (3, 7),
    (1, 3),
    (8, NULL),
    (4, 8),
    (1, 4),
    (9, NULL),
    (5, 9),
    (1, 5),
    (9, NULL),
    (10, NULL),
    (4, 10),
    (11, NULL),
    (5, 11);